language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
#after_success:
#  - make docker_build
deploy:
  provider: heroku
  app: nameless-temple-83567
  api_key: ${HEROKU_API_KEY}
